name: 1- building the workflow

on:
  push:
  workflow_dispatch:

jobs:
  echo-hello-world:
    runs-on:
      ubuntu-latest
    steps:
      - run: echo "hello-world - Runner OS $RUNNER_OS"
  echo-say-good-bye:
    runs-on:
      ubuntu-latest
    steps:
      - run: echo "bye - Runner OS $RUNNER_OS"
