name: Echo GitHub Context

on:
  push:
  workflow_dispatch:

jobs:
  echo-context:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo GitHub Context
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
