name: Trigger on Push to Specific Branches and Paths

on:
  push:
    branches:
      - 'master'     # Trigger on push to the main branch
    paths:
      - 'server/**'   # Only trigger if files in the 'src' directory are modified

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello-world - Runner OS $RUNNER_OS"
