name: Trigger on Pull Request to Multiple Branches

on:
  pull_request:
    branches:
      - 'master'     # Trigger on pull request to the main branch
      - 'develop'  # Trigger on pull request to the develop branch

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello-world - Runner OS $RUNNER_OS"
