name: Trigger on Specific Path Change

on:
  push:
    paths:
      - 'src/**'  # Only run if files in the 'src' directory are changed

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello-world - Runner OS $RUNNER_OS"
