name: Trigger on Branch Patterns for Push

on:
  push:
    branches:
      - 'main'     # Trigger on push to the main branch
      - 'develop'  # Trigger on push to the develop branch

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello-world - Runner OS $RUNNER_OS"
